/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChuyenMoiRouteImport } from './routes/chuyen-moi'
import { Route as DiaDiemRouteImport } from './routes/dia-diem'
import { Route as DinhMucRouteImport } from './routes/dinh-muc'
import { Route as PhieuRouteImport } from './routes/phieu'
import { Route as QuyCheRouteImport } from './routes/quy-che'
import { Route as PhieuIndexRouteImport } from './routes/phieu.index'
import { Route as PhieuIdRouteImport } from './routes/phieu.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChuyenMoiRoute = ChuyenMoiRouteImport.update({
  id: '/chuyen-moi',
  path: '/chuyen-moi',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDiemRoute = DiaDiemRouteImport.update({
  id: '/dia-diem',
  path: '/dia-diem',
  getParentRoute: () => rootRouteImport,
} as any)
const DinhMucRoute = DinhMucRouteImport.update({
  id: '/dinh-muc',
  path: '/dinh-muc',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuRoute = PhieuRouteImport.update({
  id: '/phieu',
  path: '/phieu',
  getParentRoute: () => rootRouteImport,
} as any)
const QuyCheRoute = QuyCheRouteImport.update({
  id: '/quy-che',
  path: '/quy-che',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuIndexRoute = PhieuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhieuRoute,
} as any)
const PhieuIdRoute = PhieuIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PhieuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chuyen-moi': typeof ChuyenMoiRoute
  '/dia-diem': typeof DiaDiemRoute
  '/dinh-muc': typeof DinhMucRoute
  '/phieu': typeof PhieuRouteWithChildren
  '/quy-che': typeof QuyCheRoute
  '/phieu/$id': typeof PhieuIdRoute
  '/phieu/': typeof PhieuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chuyen-moi': typeof ChuyenMoiRoute
  '/dia-diem': typeof DiaDiemRoute
  '/dinh-muc': typeof DinhMucRoute
  '/quy-che': typeof QuyCheRoute
  '/phieu/$id': typeof PhieuIdRoute
  '/phieu': typeof PhieuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chuyen-moi': typeof ChuyenMoiRoute
  '/dia-diem': typeof DiaDiemRoute
  '/dinh-muc': typeof DinhMucRoute
  '/phieu': typeof PhieuRouteWithChildren
  '/quy-che': typeof QuyCheRoute
  '/phieu/$id': typeof PhieuIdRoute
  '/phieu/': typeof PhieuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chuyen-moi'
    | '/dia-diem'
    | '/dinh-muc'
    | '/phieu'
    | '/quy-che'
    | '/phieu/$id'
    | '/phieu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chuyen-moi'
    | '/dia-diem'
    | '/dinh-muc'
    | '/quy-che'
    | '/phieu/$id'
    | '/phieu'
  id:
    | '__root__'
    | '/'
    | '/chuyen-moi'
    | '/dia-diem'
    | '/dinh-muc'
    | '/phieu'
    | '/quy-che'
    | '/phieu/$id'
    | '/phieu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChuyenMoiRoute: typeof ChuyenMoiRoute
  DiaDiemRoute: typeof DiaDiemRoute
  DinhMucRoute: typeof DinhMucRoute
  PhieuRoute: typeof PhieuRouteWithChildren
  QuyCheRoute: typeof QuyCheRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chuyen-moi': {
      id: '/chuyen-moi'
      path: '/chuyen-moi'
      fullPath: '/chuyen-moi'
      preLoaderRoute: typeof ChuyenMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-diem': {
      id: '/dia-diem'
      path: '/dia-diem'
      fullPath: '/dia-diem'
      preLoaderRoute: typeof DiaDiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinh-muc': {
      id: '/dinh-muc'
      path: '/dinh-muc'
      fullPath: '/dinh-muc'
      preLoaderRoute: typeof DinhMucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu': {
      id: '/phieu'
      path: '/phieu'
      fullPath: '/phieu'
      preLoaderRoute: typeof PhieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quy-che': {
      id: '/quy-che'
      path: '/quy-che'
      fullPath: '/quy-che'
      preLoaderRoute: typeof QuyCheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu/': {
      id: '/phieu/'
      path: '/'
      fullPath: '/phieu/'
      preLoaderRoute: typeof PhieuIndexRouteImport
      parentRoute: typeof PhieuRoute
    }
    '/phieu/$id': {
      id: '/phieu/$id'
      path: '/$id'
      fullPath: '/phieu/$id'
      preLoaderRoute: typeof PhieuIdRouteImport
      parentRoute: typeof PhieuRoute
    }
  }
}

interface PhieuRouteChildren {
  PhieuIdRoute: typeof PhieuIdRoute
  PhieuIndexRoute: typeof PhieuIndexRoute
}

const PhieuRouteChildren: PhieuRouteChildren = {
  PhieuIdRoute: PhieuIdRoute,
  PhieuIndexRoute: PhieuIndexRoute,
}

const PhieuRouteWithChildren = PhieuRoute._addFileChildren(PhieuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChuyenMoiRoute: ChuyenMoiRoute,
  DiaDiemRoute: DiaDiemRoute,
  DinhMucRoute: DinhMucRoute,
  PhieuRoute: PhieuRouteWithChildren,
  QuyCheRoute: QuyCheRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
